name: Security check - Trivy

on:
  workflow_dispatch:

jobs:
  build:
    name: trivy_analysys
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: action/checkout@v3

    - name: Generate tarball from image
      run: |
        docker pull nginx:latest
        docker save -o vuln-image.tar nginx:latest

    - name: Run Trivy vulnerability scanner in tarball mode
      uses: aquasecurity/trivy-action@master
      with:
        input: /github/workspace/vuln-image.tar
        severity: 'CRITICAL,HIGH'
